namespace Jellyfin.Plugin.Jellydash.Constants
{
    /// <summary>
    /// Provides constants for the playback entry table schema used by the Jellydash plugin.
    /// </summary>
    public static class PlaybackEntryConstants
    {
        /// <summary>
        /// Comma-separated list of column names for the playback entry table.
        /// </summary>
        public const string Columns = @"
            PlaybackId,
            ItemId,
            ParentItemId,
            ContentType,
            Title,
            Genres,
            Year,
            SeriesName,
            SeasonNumber,
            EpisodeNumber,
            UserId,
            UserName,
            UserPrimaryImageTag,
            ItemImageHash,
            ClientName,
            DeviceName,
            DeviceId,
            StartTime,
            EndTime,
            RuntimeTicks,
            StartPositionTicks,
            EndPositionTicks,
            IsCompleted,
            IsPaused,
            VideoCodec,
            VideoContainer,
            VideoRange,
            VideoBitrate,
            VideoBitDepth,
            VideoHeight,
            VideoWidth,
            AudioLanguage,
            AudioCodec,
            AudioLayout,
            AudioBitrate,
            AudioSampleRate,
            SubtitleIsForced,
            SubtitleIsHearingImpaired,
            SubtitleCodec,
            SubtitleLanguage,
            IsVideoDirect,
            IsAudioDirect,
            TranscodeBitrate,
            HardwareAcceleration,
            TranscodedVideoContainer,
            TranscodedVideoCodec,
            TranscodedAudioCodec,
            TranscodeReasonsJson,
            TranscodeCompletionPercentage
        ";

        /// <summary>
        /// Comma-separated list of parameter names for the playback entry table used in SQL commands.
        /// </summary>
        public const string Parameters = @"
            @PlaybackId,
            @ItemId,
            @ParentItemId,
            @ContentType,
            @Title,
            @Genres,
            @Year,
            @SeriesName,
            @SeasonNumber,
            @EpisodeNumber,
            @UserId,
            @UserName,
            @UserPrimaryImageTag,
            @ItemImageHash,
            @ClientName,
            @DeviceName,
            @DeviceId,
            @StartTime,
            @EndTime,
            @RuntimeTicks,
            @StartPositionTicks,
            @EndPositionTicks,
            @IsCompleted,
            @IsPaused,
            @VideoCodec,
            @VideoContainer,
            @VideoRange,
            @VideoBitrate,
            @VideoBitDepth,
            @VideoHeight,
            @VideoWidth,
            @AudioLanguage,
            @AudioCodec,
            @AudioLayout,
            @AudioBitrate,
            @AudioSampleRate,
            @SubtitleIsForced,
            @SubtitleIsHearingImpaired,
            @SubtitleCodec,
            @SubtitleLanguage,
            @IsVideoDirect,
            @IsAudioDirect,
            @TranscodeBitrate,
            @HardwareAcceleration,
            @TranscodedVideoContainer,
            @TranscodedVideoCodec,
            @TranscodedAudioCodec,
            @TranscodeReasonsJson,
            @TranscodeCompletionPercentage
        ";

        /// <summary>
        /// SQL SET clause for updating playback entry fields in the database.
        /// </summary>
        public const string UpdateSetClause = @"
            PlaybackId = @PlaybackId,
            ItemId = @ItemId,
            ParentItemId = @ParentItemId,
            ContentType = @ContentType,
            Title = @Title,
            Genres = @Genres,
            Year = @Year,
            SeriesName = @SeriesName,
            SeasonNumber = @SeasonNumber,
            EpisodeNumber = @EpisodeNumber,
            UserId = @UserId,
            UserName = @UserName,
            UserPrimaryImageTag = @UserPrimaryImageTag,
            ClientName = @ClientName,
            DeviceName = @DeviceName,
            DeviceId = @DeviceId,
            StartTime = @StartTime,
            EndTime = @EndTime,
            RuntimeTicks = @RuntimeTicks,
            StartPositionTicks = @StartPositionTicks,
            EndPositionTicks = @EndPositionTicks,
            IsCompleted = @IsCompleted,
            IsPaused = @IsPaused,
            VideoCodec = @VideoCodec,
            VideoContainer = @VideoContainer,
            VideoRange = @VideoRange,
            VideoBitrate = @VideoBitrate,
            VideoBitDepth = @VideoBitDepth,
            VideoHeight = @VideoHeight,
            VideoWidth = @VideoWidth,
            AudioLanguage = @AudioLanguage,
            AudioCodec = @AudioCodec,
            AudioLayout = @AudioLayout,
            AudioBitrate = @AudioBitrate,
            AudioSampleRate = @AudioSampleRate,
            SubtitleIsForced = @SubtitleIsForced,
            SubtitleIsHearingImpaired = @SubtitleIsHearingImpaired,
            SubtitleCodec = @SubtitleCodec,
            SubtitleLanguage = @SubtitleLanguage,
            IsVideoDirect = @IsVideoDirect,
            IsAudioDirect = @IsAudioDirect,
            TranscodeBitrate = @TranscodeBitrate,
            HardwareAcceleration = @HardwareAcceleration,
            TranscodedVideoContainer = @TranscodedVideoContainer,
            TranscodedVideoCodec = @TranscodedVideoCodec,
            TranscodedAudioCodec = @TranscodedAudioCodec,
            TranscodeReasonsJson = @TranscodeReasonsJson,
            TranscodeCompletionPercentage = @TranscodeCompletionPercentage
        ";
    }
}
