CREATE TABLE IF NOT EXISTS Activities (
    Id                          INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId                      TEXT    NOT NULL,
    UserName                    TEXT    NOT NULL,
    UserImageUrl                TEXT    NULL,
    ItemId                      TEXT    NOT NULL,
    ClientName                  TEXT    NULL,
    DeviceName                  TEXT    NULL,
    MediaType                   TEXT    NOT NULL,
    ItemName                    TEXT    NOT NULL,
    SeriesName                  TEXT    NULL,
    SeasonNumber                INTEGER NULL,
    EpisodeNumber               INTEGER NULL,
    ProductionYear              INTEGER NULL,
    PrimaryGenre                TEXT    NULL,
    PrimaryImagePath            TEXT    NULL,
    StartUtc                    TEXT    NOT NULL,
    EndUtc                      TEXT    NOT NULL,
    RuntimeTicks                INTEGER NULL,
    StartPositionTicks          INTEGER NULL,
    EndPositionTicks            INTEGER NULL,
    StartPercentage             REAL    NOT NULL,
    EndPercentage               REAL    NOT NULL,
    IsDownload                  INTEGER NOT NULL,
    DownloadSizeBytes           INTEGER NULL,
    DownloadedBytes             INTEGER NULL,
    DownloadProgressPercent     REAL    NULL,
    Bitrate                     INTEGER NULL,
    IsVideoDirectStream         INTEGER NOT NULL,
    IsAudioDirectStream         INTEGER NOT NULL,
    IsTranscoding               INTEGER NOT NULL,
    TranscodeVideoCodec         TEXT    NULL,
    TranscodeAudioCodec         TEXT    NULL,
    TranscodeContainer          TEXT    NULL,
    TranscodeHardwareAcceleration TEXT NULL
);
