// Mocks generated by Mockito 5.4.6 from annotations
// in jellydash/test/screens/dashboard_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:jellydash/services/jellyfin_api_service.dart' as _i3;
import 'package:jellydash/types/activity_response.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeActivityResponse_0 extends _i1.SmartFake
    implements _i2.ActivityResponse {
  _FakeActivityResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [JellyfinApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockJellyfinApiService extends _i1.Mock
    implements _i3.JellyfinApiService {
  MockJellyfinApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i5.Future<_i2.ActivityResponse> fetchActivity(
    bool? includeActive,
    int? limit,
    String? cursor,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchActivity,
          [
            includeActive,
            limit,
            cursor,
          ],
        ),
        returnValue:
            _i5.Future<_i2.ActivityResponse>.value(_FakeActivityResponse_0(
          this,
          Invocation.method(
            #fetchActivity,
            [
              includeActive,
              limit,
              cursor,
            ],
          ),
        )),
      ) as _i5.Future<_i2.ActivityResponse>);
}
