name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  plugin-test:
    name: Plugin tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET dependencies
        working-directory: plugin
        run: dotnet restore Jellyfin.Plugin.Jellydash.sln

      - name: Run .NET tests
        working-directory: plugin
        run: dotnet test Jellyfin.Plugin.Jellydash.sln --configuration Release --collect:"XPlat Code Coverage"

  test-flutter:
    name: Flutter tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test
